language: java
jdk:
  - openjdk 11

branches:
  only:
    - master

cache:
  directiories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - 123dbstjd@naver.com