spring:
  profiles:
    include: real-db

  jackson:
    deserialization:
      fail-on-unknown-properties: true # 역직렬화 하는과정에서 필요없는 값이 있다면 에러를 내보낸다

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8081