spring:
  datasource:
    url: jdbc:mariadb://jys-db-1.cdqfawu1zqg7.ap-northeast-2.rds.amazonaws.com:3306/jys_springboot
    username: jys
    password: sjop6390
    driver-class-name: org.mariadb.jdbc.Driver