spring:
  profiles:
    active: dev

  jackson:
    deserialization:
      fail-on-unknown-properties: true # 역직렬화 하는과정에서 필요없는 값이 있다면 에러를 내보낸다

  datasource:
    url: jdbc:h2:tcp://localhost/~/firstporject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
