spring:
#    url: jdbc:mariadb://localhost/jys_springboot
#    username: root
#    password: sjop6390
#    driver-class-name: org.mariadb.jdbc.Driver
  datasource:
    url: jdbc:mariadb://jys-db-1.cdqfawu1zqg7.ap-northeast-2.rds.amazonaws.com/jys_springboot
    username: jys
    password: sjop6390
    driver-class-name: org.mariadb.jdbc.Driver